queue_rules:
  - name: Default merge queue
    autoqueue: true
    draft_bot_account: imbhargav5
    merge_bot_account: imbhargav5
    update_bot_account: imbhargav5
    merge_method: merge
    merge_conditions:
      - check-success=GitGuardian Security Checks
      - or:
          - check-success=Run vitest suite
          - check-skipped=Run vitest suite
      - or:
          - check-success=Playwright E2E
          - check-skipped=Playwright E2E

merge_queue:
  max_parallel_checks: 10

merge_protections:
  - name: Do not merge outdated PRs
    description: Make sure PRs are almost up to date before merging
    if:
      - base = main
    success_conditions:
      - "#commits-behind <= 10"

merge_protections_settings:
  reporting_method: check-runs
