import { createStore } from "jotai/vanilla";
import { describe, expect, it } from "vitest";
import { appNameAtom, isMacOSAtom, windowTypeAtom } from "./app";
import {
	imageBackgroundTypeAtom,
	imageBorderRadiusAtom,
	imageExportingAtom,
	imageGradientAtom,
	imageNaturalHeightAtom,
	imageNaturalWidthAtom,
	imagePaddingAtom,
	imageShadowIntensityAtom,
	imageSolidColorAtom,
	imageSrcAtom,
	imageWallpaperAtom,
	imageWallpaperPreviewPathsAtom,
} from "./imageEditor";
import {
	hasSelectedSourceAtom,
	isCapturingAtom,
	permissionOnboardingRequestingAtom,
	permissionOnboardingStepAtom,
	recordingElapsedAtom,
	recordingStartAtom,
	screenRecordingAwaitingRelaunchAtom,
	screenshotModeAtom,
	selectedSourceAtom,
} from "./launch";
import { isCheckingPermissionsAtom, type PermissionState, permissionsAtom } from "./permissions";
import {
	cameraDeviceIdAtom,
	cameraEnabledAtom,
	microphoneDeviceIdAtom,
	microphoneEnabledAtom,
	recordingActiveAtom,
	systemAudioEnabledAtom,
} from "./recording";
import {
	settingsActiveTabAtom,
	settingsBackgroundTabAtom,
	settingsCustomImagesAtom,
	settingsGradientAtom,
	settingsSelectedColorAtom,
	settingsShowCropModalAtom,
} from "./settingsPanel";
import {
	isShortcutsConfigOpenAtom,
	shortcutCaptureForAtom,
	shortcutConflictAtom,
	shortcutsAtom,
	shortcutsDraftAtom,
} from "./shortcuts";
import {
	sourceSelectorTabAtom,
	sourcesAtom,
	sourcesLoadingAtom,
	windowsLoadingAtom,
} from "./sourceSelector";
import {
	timelineCustomAspectHeightAtom,
	timelineCustomAspectWidthAtom,
	timelineDraggingKeyframeIdAtom,
	timelineKeyframesAtom,
	timelinePlaybackCursorDraggingAtom,
	timelineRangeAtom,
	timelineScrollLabelsAtom,
	timelineSelectedKeyframeIdAtom,
} from "./timeline";
import {
	updaterDialogOpenAtom,
	updaterDownloadProgressAtom,
	updaterErrorAtom,
	updaterReleaseNotesAtom,
	updaterStatusAtom,
	updaterVersionAtom,
} from "./updater";
import {
	addCustomFontDialogOpenAtom,
	addCustomFontImportUrlAtom,
	addCustomFontLoadingAtom,
	addCustomFontNameAtom,
	annotationCustomFontsAtom,
	annotationRegionsAtom,
	aspectRatioAtom,
	audioMutedAtom,
	audioVolumeAtom,
	backgroundBlurAtom,
	borderRadiusAtom,
	connectZoomsAtom,
	cropControlDragHandleAtom,
	cropControlDragStartAtom,
	cropControlInitialCropAtom,
	cropRegionAtom,
	cursorSettingsAtom,
	durationAtom,
	exportDialogShowSuccessAtom,
	exportErrorAtom,
	exportedFilePathAtom,
	exportFormatAtom,
	exportProgressAtom,
	exportQualityAtom,
	facecamSettingsAtom,
	gifFrameRateAtom,
	gifLoopAtom,
	gifSizePresetAtom,
	hasPendingExportSaveAtom,
	isExportingAtom,
	isPlayingAtom,
	lastSavedSnapshotAtom,
	paddingAtom,
	playbackReadyAtom,
	selectedAnnotationIdAtom,
	selectedSpeedIdAtom,
	selectedTrimIdAtom,
	selectedZoomIdAtom,
	shadowIntensityAtom,
	showExportDialogAtom,
	showShortcutsDialogAtom,
	speedRegionsAtom,
	trimRegionsAtom,
	videoErrorAtom,
	videoLoadingAtom,
	videoPathAtom,
	videoPlaybackAnnotationVisibilityTickAtom,
	videoPlaybackCursorOverlayReadyAtom,
	videoPlaybackFacecamReadyAtom,
	videoPlaybackFirstFrameReadyAtom,
	videoPlaybackMetadataReadyAtom,
	videoPlaybackPixiReadyAtom,
	videoPlaybackResolvedWallpaperAtom,
	videoSourcePathAtom,
	videoWallpaperAtom,
	zoomMotionBlurAtom,
	zoomRegionsAtom,
} from "./videoEditor";

describe("atom defaults", () => {
	it.each([
		["app name", appNameAtom, "Open Recorder"],
		["window type", windowTypeAtom, ""],
		["mac platform", isMacOSAtom, false],
		["launch capture", isCapturingAtom, false],
		["launch screenshot mode", screenshotModeAtom, null],
		["launch selected source", selectedSourceAtom, "Main Display"],
		["launch has selected source", hasSelectedSourceAtom, true],
		["launch recording start", recordingStartAtom, null],
		["launch recording elapsed", recordingElapsedAtom, 0],
		["permission onboarding step", permissionOnboardingStepAtom, "welcome"],
		["permission onboarding requesting", permissionOnboardingRequestingAtom, false],
		["screen recording awaiting relaunch", screenRecordingAwaitingRelaunchAtom, false],
		["recording active", recordingActiveAtom, false],
		["microphone enabled", microphoneEnabledAtom, false],
		["microphone device", microphoneDeviceIdAtom, undefined],
		["system audio enabled", systemAudioEnabledAtom, false],
		["camera enabled", cameraEnabledAtom, false],
		["camera device", cameraDeviceIdAtom, undefined],
		[
			"permissions",
			permissionsAtom,
			{
				screenRecording: "checking",
				microphone: "checking",
				camera: "checking",
				accessibility: "checking",
			} satisfies PermissionState,
		],
		["permissions loading", isCheckingPermissionsAtom, true],
		["shortcuts config", shortcutsAtom, expect.any(Object)],
		["shortcuts open", isShortcutsConfigOpenAtom, false],
		["shortcuts draft", shortcutsDraftAtom, expect.any(Object)],
		["shortcut capture", shortcutCaptureForAtom, null],
		["shortcut conflict", shortcutConflictAtom, null],
		["settings tab", settingsActiveTabAtom, "appearance"],
		["settings background tab", settingsBackgroundTabAtom, "image"],
		["settings custom images", settingsCustomImagesAtom, []],
		["settings gradient", settingsGradientAtom, expect.any(String)],
		["settings selected color", settingsSelectedColorAtom, "#ADADAD"],
		["settings crop modal", settingsShowCropModalAtom, false],
		["source selector tab", sourceSelectorTabAtom, "screens"],
		["source selector loading", sourcesLoadingAtom, true],
		["source selector windows loading", windowsLoadingAtom, true],
		["sources", sourcesAtom, []],
		["timeline range", timelineRangeAtom, { start: 0, end: 0 }],
		["timeline keyframes", timelineKeyframesAtom, []],
		["timeline selected keyframe", timelineSelectedKeyframeIdAtom, null],
		["timeline dragging keyframe", timelineDraggingKeyframeIdAtom, null],
		["timeline playback cursor dragging", timelinePlaybackCursorDraggingAtom, false],
		["timeline width", timelineCustomAspectWidthAtom, "16"],
		["timeline height", timelineCustomAspectHeightAtom, "9"],
		[
			"timeline labels",
			timelineScrollLabelsAtom,
			{
				pan: "Shift + Ctrl + Scroll",
				zoom: "Ctrl + Scroll",
			},
		],
		["updater status", updaterStatusAtom, "idle"],
		["updater dialog", updaterDialogOpenAtom, false],
		["updater version", updaterVersionAtom, null],
		["updater notes", updaterReleaseNotesAtom, null],
		["updater progress", updaterDownloadProgressAtom, 0],
		["updater error", updaterErrorAtom, null],
		["video path", videoPathAtom, null],
		["video source path", videoSourcePathAtom, null],
		["video loading", videoLoadingAtom, true],
		["video ready", playbackReadyAtom, false],
		["video error", videoErrorAtom, null],
		["video playback pixi ready", videoPlaybackPixiReadyAtom, false],
		["video playback metadata ready", videoPlaybackMetadataReadyAtom, false],
		["video playback first frame ready", videoPlaybackFirstFrameReadyAtom, false],
		["video playback cursor overlay ready", videoPlaybackCursorOverlayReadyAtom, false],
		["video playback facecam ready", videoPlaybackFacecamReadyAtom, false],
		["video playback annotation tick", videoPlaybackAnnotationVisibilityTickAtom, 0],
		["video playback resolved wallpaper", videoPlaybackResolvedWallpaperAtom, null],
		["video playing", isPlayingAtom, false],
		["video duration", durationAtom, 0],
		["video wallpaper", videoWallpaperAtom, expect.any(String)],
		["video audio muted", audioMutedAtom, false],
		["video audio volume", audioVolumeAtom, 1],
		["video shadow", shadowIntensityAtom, 0.67],
		["video blur", backgroundBlurAtom, 0],
		["video zoom blur", zoomMotionBlurAtom, 0.35],
		["video connect zooms", connectZoomsAtom, true],
		[
			"video cursor settings",
			cursorSettingsAtom,
			{
				showCursor: true,
				loopCursor: false,
				cursorSize: 3,
				cursorSmoothing: 0.67,
				cursorMotionBlur: 0.35,
				cursorClickBounce: 2.5,
			},
		],
		["video border radius", borderRadiusAtom, 12.5],
		["video padding", paddingAtom, 50],
		["video crop", cropRegionAtom, { x: 0, y: 0, width: 1, height: 1 }],
		["crop control drag handle", cropControlDragHandleAtom, null],
		["crop control drag start", cropControlDragStartAtom, { x: 0, y: 0 }],
		["crop control initial crop", cropControlInitialCropAtom, { x: 0, y: 0, width: 1, height: 1 }],
		["video facecam", facecamSettingsAtom, expect.any(Object)],
		["video zoom regions", zoomRegionsAtom, []],
		["video selected zoom", selectedZoomIdAtom, null],
		["video trim regions", trimRegionsAtom, []],
		["video selected trim", selectedTrimIdAtom, null],
		["video speed regions", speedRegionsAtom, []],
		["video selected speed", selectedSpeedIdAtom, null],
		["video annotation regions", annotationRegionsAtom, []],
		["video selected annotation", selectedAnnotationIdAtom, null],
		["video exporting", isExportingAtom, false],
		["video export progress", exportProgressAtom, null],
		["video export error", exportErrorAtom, null],
		["video export dialog", showExportDialogAtom, false],
		["video export success", exportDialogShowSuccessAtom, false],
		["video shortcuts dialog", showShortcutsDialogAtom, false],
		["video aspect ratio", aspectRatioAtom, "16:9"],
		["video export quality", exportQualityAtom, "good"],
		["video export format", exportFormatAtom, "mp4"],
		["video gif frame rate", gifFrameRateAtom, 15],
		["video gif loop", gifLoopAtom, true],
		["video gif size", gifSizePresetAtom, "medium"],
		["video exported file path", exportedFilePathAtom, undefined],
		["video pending save", hasPendingExportSaveAtom, false],
		["video last saved snapshot", lastSavedSnapshotAtom, null],
		["custom font dialog", addCustomFontDialogOpenAtom, false],
		["custom font import url", addCustomFontImportUrlAtom, ""],
		["custom font name", addCustomFontNameAtom, ""],
		["custom font loading", addCustomFontLoadingAtom, false],
		["annotation custom fonts", annotationCustomFontsAtom, []],
		["image src", imageSrcAtom, null],
		["image width", imageNaturalWidthAtom, 0],
		["image height", imageNaturalHeightAtom, 0],
		["image background", imageBackgroundTypeAtom, "wallpaper"],
		["image wallpaper", imageWallpaperAtom, expect.any(String)],
		["image gradient", imageGradientAtom, expect.any(String)],
		["image solid color", imageSolidColorAtom, "#2563EB"],
		["image padding", imagePaddingAtom, 48],
		["image border radius", imageBorderRadiusAtom, 12],
		["image shadow", imageShadowIntensityAtom, 0.6],
		["image wallpaper previews", imageWallpaperPreviewPathsAtom, []],
		["image exporting", imageExportingAtom, false],
	])("defaults %s", (_label, atom, expected) => {
		const store = createStore();
		expect(store.get(atom as never)).toEqual(expected);
	});

	it("isolates writes between stores", () => {
		const firstStore = createStore();
		const secondStore = createStore();

		firstStore.set(appNameAtom, "Recorder Alpha");
		firstStore.set(isMacOSAtom, true);

		expect(firstStore.get(appNameAtom)).toBe("Recorder Alpha");
		expect(secondStore.get(appNameAtom)).toBe("Open Recorder");
		expect(firstStore.get(isMacOSAtom)).toBe(true);
		expect(secondStore.get(isMacOSAtom)).toBe(false);
	});
});
